### ISSUE TITLE
Error: TouchEvent.obtain( <-

### ISSUE THREAD

**Issue by Lizhooh** [879479119/react-native-shadow#12]
react-native run-android  BUILD FAILED

React Native 0.44 

```js
react-native-svg\android\src\main\java\com\horcrux\svg\SvgView.java:130: 错误: 无法将类 TouchEvent中的方法 obtain应用到给定类型;
            TouchEvent.obtain(
                      ^
  需要: int,TouchEventType,MotionEvent,long,float,float,TouchEventCoalescingKeyHelper
  找到: int,TouchEventType,MotionEvent,float,float,TouchEventCoalescingKeyHelper
  原因: 实际参数列表和形式参数列表长度不同
1 个错误
```

**Comment by DoruFurtuna** [comment]
The problem was solved in latest version of [@react-native-svg](https://github.com/react-native-community/react-native-svg). You can just install it manually with `npm install react-native-svg --save`.

**Comment by DoruFurtuna** [comment]
Created a PR #13

**Comment by 0mkara** [comment]
![photo_2017-06-04_18-48-31](https://cloud.githubusercontent.com/assets/13261372/26761953/89ddb5e6-4956-11e7-93b7-2048c175a006.jpg)
I am getting this error after I install latest version of react-native-svg.
