### ISSUE TITLE
Failed to install and build

### ISSUE THREAD

**Issue by markortiz** [879479119/react-native-shadow#14]
First I try to link it via `rnpm` and `react-native link`.
Then it failed and I try to manually install it following your instructions and still got this error.
```
"react-native": "0.44.0",
"react-native-shadow": "^1.1.2",
```
```
/myNewApp/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/SvgView.java:130: error: method obtain in class TouchEvent cannot be applied to given types;
            TouchEvent.obtain(
                      ^
  required: int,TouchEventType,MotionEvent,long,float,float,TouchEventCoalescingKeyHelper
  found: int,TouchEventType,MotionEvent,float,float,TouchEventCoalescingKeyHelper
  reason: actual and formal argument lists differ in length
1 error
:react-native-svg:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.
```

**Comment by 879479119** [comment]
Hi, I have released `react-native-shadow@1.2.1`, which remove the dependency of a certain version of `react-native-svg`, so you must install the the correct version of it according to the version of your `react` and `react-native` [doc](https://github.com/react-native-community/react-native-svg)
