### ISSUE TITLE
 error: package com.facebook.yoga does not exist

### ISSUE THREAD

**Issue by gungungun93** [879479119/react-native-shadow#2]
I got this error 
/node_modules/react-native-svg/android/src/main/java/com/horcrux/svg/SvgViewManager.java:14: error: package com.facebook.yoga does not exist 
import com.facebook.yoga.YogaMeasureMode;
                                               ^

**Comment by 879479119** [comment]
maybe `react-native-svg` was downloaded incorrectly, or its author updated something, you can check the newest version of `react-native-svg`.   since I have never met question about `yoga` before, hope these can help

**Comment by gungungun93** [comment]
thank you for your respond. I just found the solution by updating react and react-native package.
