### ISSUE TITLE
Error while updating property 'strokeWidth'

### ISSUE THREAD

**Issue by rulgf** [879479119/react-native-shadow#21]
Hi,
I´m trying to use this library in my project but found this error:

![_20171016_140402](https://user-images.githubusercontent.com/9823771/31630039-ffb45512-b27a-11e7-9bac-c753fd0585ff.JPG)

I´m using expo.

Versions:
```
"react-native": 0.47.1
"react": "16.0.0-alpha.12",
"react-native-shadow": "^1.2.1",
"react-native-svg": "^6.0.0-rc1",
```

**Comment by rulgf** [comment]
I found the solution if someone else needed,
Expo comes with the `react-native-svg` preinstalled. But in order to import this library you need to insert

`import { Svg } from 'expo';`

So to use this library with expo and the preinstalled library of svg you will need to change the imports of the code and replace some of the tags like:

`<Path>` to `<Svg.Path>`

**Comment by Noitidart** [comment]
Any tips @rulgf for latest expo?
