### ISSUE TITLE
Each child in an array or iterator should have a unique "key" prop. Check the render method of `BoxShadow`. See https://fb.me/react-warning-keys for more information.

### ISSUE THREAD

**Issue by Lxxyx** [879479119/react-native-shadow#4]
Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `BoxShadow`. See https://fb.me/react-warning-keys for more information.

BoxShadow._this.render	@	BoxShadow.js:32

**Comment by jimthedev** [comment]
I also had this issue. I think my PR should fix it. @879479119 can you review?

**Comment by agilests** [comment]
I see the source, you add the prop 'key',but the warning remains!
<Stop offset="0" stopColor={color} stopOpacity={opacity} key={key+'Linear0'} />,
<Stop offset="1" stopColor={color} stopOpacity="0" key={key+'Linear1'} />

My dependencies is:
react-native-shadow:^1.2.1
react-native-svg:^6.0.0
