### ISSUE TITLE
how to change shadow backgroundColor

### ISSUE THREAD

**Issue by JourneyL** [879479119/react-native-shadow#5]
i set x,y and appear a box that backgroundColor is black  ,how to change the backgroundColor of this box ?

**Comment by 879479119** [comment]
have you pass an `color` like '#999' to the conponent ?

**Comment by 879479119** [comment]
没有啊~   RN适用范围还是很有限的，一根动画扯上关系就很卡了，视频播放也不现实只有调用原生的组件。       包刚刚更新到了1.1.1    update一下试试~

**Comment by JourneyL** [comment]
3q  我试一下子
